apiVersion: v1
kind: Service
metadata:
  name: yt-llm-svc
  namespace: music
  labels:
    app: yt-llm
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"   # matches container port
spec:
  selector:
    app: yt-llm
  ports:
    - name: http
      port: 80
      targetPort: 8000
